### ISSUE TITLE
Import option not available

### ISSUE THREAD

**Issue by krosisthearcher** [PrismaticFlower/SWBF-msh-Blender-IO#7]
I installed the addon, and everything seems to work except for the one thing i wanna use - importing. i have enabled the addon, but theres no new import option in file > import. there is an swbf option in exporting though.  I tried using the file > open option, but it gives me a ".msh not supported" error. What can I do?

**Comment by PrismaticFlower** [comment]
Strange! Is this with the latest version? You can find it here if you're not sure: https://github.com/PrismaticFlower/SWBF-msh-Blender-IO/releases/latest

**Comment by krosisthearcher** [comment]
yup! but actually i already found a fix on the discord! i had to use the pre release: https://github.com/PrismaticFlower/SWBF-msh-Blender-IO/releases/tag/1.0.0-rc

someone else already had the exact same issue. 
Thank you for reachng out so soon :)

I do have an another question though, if you dont mind:
i imported a trooper .msh  into blender, but his animation rig is very chaotic (like tens of those "bones" sticking out of his body in weird places - unlike any normal rig ive seen before) - is that normal? i guess its an old game so maybe things were done diffrent then. How can i also apply .msh animations (lets say reload for example) to the model in blender?

**Comment by WHSnyder** [comment]
@krosisthearcher 

You do not have to use the pre-release, the latest release has worked for plenty of people.

As for the rig, it is chaotic because SWBF2 models were mostly created in a program where the bones can be connected via arbitrary axis choices.  However Blender always uses the y-axis for connected bones.  If I were to reconnect the bones tip-to-tail when they are imported, that would break compatibility with existing animations for that rig, since reconnecting the bones means changing their orientation.  It is possible to do this and record the information necessary for maintaining animation compatibility (and I've gotten about half way there) but I just don't have the time these days to finish it up.  And it would likely cause problems in other unforeseen ways.

**Comment by WHSnyder** [comment]
@krosisthearcher 

Make sure you just download the zip and when you browse for the file to install, just select the zip itself.  _Don't unzip at any time._

**Comment by krosisthearcher** [comment]
Alright, thanks a lot for the info. Turns out that some of the bones appeared because of the animation models, so its not so unnatural as i said before, but yes it seems far from the standard. Also yes, i did unzip the plugin pack, my bad. I probably missed the info (its easy to get lost with all the technical language, English isn't my native language, and it was very late at night at that point and i was tired from all the troubleshooting). Im gonna try to install it again as a zip file. Thank you again.
What i didn't get from your message though, is:
Can i still apply the animation from the game with the rig that way? And can i also still use it to animate it myself? I mean i get it that its technically compatible with the game since you didn't change it in the import, but is it compatible with blender? (If that makes sense 😅) i still need to learn a bunch about animation so please be patient with me
Thank you for any help.

**Comment by WHSnyder** [comment]
No worries man!  Language barrier issues are common in these contexts so don't sweat it.  

If you select the armature then go to the import menu, check the animation only option, then you can import animations in .zaabin or .msh files and they will be applied to the armature.  You can also create new ones yourself.  The rig may look strange but it is fully animatable and compatible with Blender.
